services:
  tubify-external-api:
    image: tubify-external-api
    container_name: tubify-external-api
    restart: unless-stopped
    expose:
      - "8000"
    networks:
      - tubify-net
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}

networks:
  tubify-net:
    external: true