services:
  tubify-external-api:
    image: tubify-external-api
    container_name: tubify-external-api
    restart: unless-stopped
    expose:
      - "8000"
    networks:
      - tubify-net
    build:
     context: .
     dockerfile: Dockerfile
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

networks:
  tubify-net:
    external: true
